language: c

sudo: required

matrix:
  include:
    - os: linux
      env: BUILD_TYPE=astyle
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang

script:
  - ./ci/travis/run_build.sh
